name: Api CI/CD

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      run: echo  Setup .NET Core
      
    - name: Build
      run: echo  Build
      
    - name: Publish
      run: echo  Publish
      
    - name: Zip Functions Package
      run: echo  Zip Functions Package
      
    - name: Upload Deployment Zip
      run: echo  Upload Deployment Zip
       
    - name: Upload Deployment Script
      run: echo  Upload Deployment Script
      
  deploy_to_dev:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    steps:
    - name: Download a Deployment Zip
      run: echo  Upload Deployment Script

    - name: digger run
      uses: diggerhq/digger@env-promotions
      with:
        setup-aws: true
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Download a Deployment Script
      run: echo  Upload Deployment Script
      
    - name: Azure Login
      run: echo  Upload Deployment Script
      
    - name: Azure Deploy Resources
      run: echo  Upload Deployment Script
          
  deploy_to_prod:
    runs-on: ubuntu-latest
    needs: deploy_to_dev
    if: github.event_name != 'pull_request'
    environment: prod
    steps:
    - name: Download a Deployment Zip
      run: echo  Download a Deployment Zip
      
    - name: Download a Deployment Script
      run: echo  Download a Deployment Script
      
    - name: Azure Login
      run: echo  Azure Login
      
    - name: Azure Deploy Resources
      if: github.event_name != 'pull_request'
      run: echo Azure Deploy Resources  
